// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PackageReferenceVersionToAttributeExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageReferenceVersionToAttributeExtensionString = "32c53199-ebbf-4453-bf5c-4f44f2bb3c93";
        public static Guid guidPackageReferenceVersionToAttributeExtension = new Guid(guidPackageReferenceVersionToAttributeExtensionString);

        public const string guidPackageReferenceVersionToAttributeExtensionCmdSetString = "0c128779-7aa4-463a-82f5-8e6eb5cc0412";
        public static Guid guidPackageReferenceVersionToAttributeExtensionCmdSet = new Guid(guidPackageReferenceVersionToAttributeExtensionCmdSetString);

        public const string guidPackageReferenceVersionToAttributeExtensionUIRuleString = "e309983d-aa3b-4faa-a8db-96923c2c0d90";
        public static Guid guidPackageReferenceVersionToAttributeExtensionUIRule = new Guid(guidPackageReferenceVersionToAttributeExtensionUIRuleString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageReferenceVersionToAttributeMenuGroup = 0x0001;
        public const int PackageReferenceVersionToAttributeCommand = 0x0100;
    }
}